baseURL = "https://arne.codes/"
languageCode = "en-us"
title = "Arne Bahlo"
theme = "marked"
copyright = "2018 Arne Bahlo"
PygmentsStyle = "github"

[params]
  author = "Arne Bahlo"
  description = "The personal website of Arne Bahlo"

[[menu.main]]
  name = "About"
  url = "/about"
[[menu.main]]
  name = "RSS"
  url = "/index.xml"
